<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <TargetFrameworks>$(TfmGroupDotNetWindows)</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Blizzard.j API implemented in C#.</Description>
    <PackageTags>api;blizzard;modding;warcraft3;wc3</PackageTags>
  </PropertyGroup>

  <ItemGroup Condition="'$(PACK)'!='true'">
    <ProjectReference Include="..\War3Net.Runtime.Api.Common\War3Net.Runtime.Api.Common.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(PACK)'=='true'">
    <PackageReference Include="War3Net.Runtime.Api.Common" />
  </ItemGroup>

</Project>
