global using System;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Diagnostics.CodeAnalysis;
global using System.IO;
global using System.Linq;
global using System.Text;
global using War3Net.CodeAnalysis.VJass.Extensions;
global using War3Net.CodeAnalysis.VJass.Syntax;