// ------------------------------------------------------------------------------
// <copyright file="LuaScriptCompiler.cs" company="Drake53">
// Licensed under the MIT license.
// See the LICENSE file in the project root for more information.
// </copyright>
// ------------------------------------------------------------------------------

using System;

namespace War3Net.Build.Script
{
    internal sealed class LuaScriptCompiler : ScriptCompiler
    {
        public LuaScriptCompiler(ScriptCompilerOptions options)
            : base(options)
        {
            throw new NotImplementedException();
        }

        public override void BuildAutogeneratedCode(out string globalsFilePath, out string mainFunctionFilePath, out string configFunctionFilePath)
        {
            throw new NotImplementedException();
        }

        public override CompileResult Compile(out string scriptFilePath, params string[] additionalSourceFiles)
        {
            throw new NotImplementedException();
        }

        public override void CompileSimple(out string scriptFilePath, params string[] additionalSourceFiles)
        {
            throw new NotImplementedException();
        }
    }
}