// ------------------------------------------------------------------------------
// <copyright file="ScriptCompiler.cs" company="Drake53">
// Licensed under the MIT license.
// See the LICENSE file in the project root for more information.
// </copyright>
// ------------------------------------------------------------------------------

namespace War3Net.Build.Script
{
    internal abstract class ScriptCompiler
    {
        private readonly ScriptCompilerOptions _options;

        protected ScriptCompiler(ScriptCompilerOptions options)
        {
            _options = options;
        }

        protected ScriptCompilerOptions Options => _options;

        public abstract void BuildAutogeneratedCode(out string globalsFilePath, out string mainFunctionFilePath, out string configFunctionFilePath);

        public abstract CompileResult Compile(out string scriptFilePath, params string[] additionalSourceFiles);

        // todo: not abstract? (since the implementation for jass and C# barely differs)
        public abstract void CompileSimple(out string scriptFilePath, params string[] additionalSourceFiles);
    }
}