<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TfmGroupDotNet)</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Parse replay (.w3g) files.</Description>
    <PackageTags>modding;replay;w3g;warcraft3;wc3</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" />
    <PackageReference Include="MessagePackAnalyzer" />
  </ItemGroup>

  <ItemGroup Condition="'$(PACK)'!='true'">
    <ProjectReference Include="..\War3Net.IO.Compression\War3Net.IO.Compression.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(PACK)'=='true'">
    <PackageReference Include="War3Net.IO.Compression" />
  </ItemGroup>

</Project>
