<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TfmGroupDotNet)</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Regenerate war3map files from a Warcraft III map script.</Description>
    <PackageTags>decompiler;jass;modding;war3map;warcraft3;wc3</PackageTags>
  </PropertyGroup>

  <ItemGroup Condition="'$(Configuration)'=='Debug'">
    <ProjectReference Include="..\War3Net.Build.Core\War3Net.Build.Core.csproj" />
    <ProjectReference Include="..\War3Net.CodeAnalysis.Jass\War3Net.CodeAnalysis.Jass.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'=='Release'">
    <PackageReference Include="War3Net.Build.Core" />
    <PackageReference Include="War3Net.CodeAnalysis.Jass" />
  </ItemGroup>

</Project>
