<Project>
  <ImportGroup>
    <Import Project="../Directory.Build.props" />
  </ImportGroup>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <DefineConstants Condition="'$(ENABLE_FLAKY_TESTS)' == 'true'">$(DefineConstants);ENABLE_FLAKY_TESTS</DefineConstants>
    <DefineConstants Condition="'$(ENABLE_ONLINE_TESTS)' == 'true'">$(DefineConstants);ENABLE_ONLINE_TESTS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' != 'War3Net.TestTools.UnitTesting'">
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
  </ItemGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' != 'War3Net.TestTools.UnitTesting'">
    <ProjectReference Include="..\War3Net.TestTools.UnitTesting\War3Net.TestTools.UnitTesting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <GlobalAnalyzerConfigFiles Include="$(MSBuildThisFileDirectory)../.config/analyzers/CA.tests.globalconfig" />
    <GlobalAnalyzerConfigFiles Include="$(MSBuildThisFileDirectory)../.config/analyzers/SA.tests.globalconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="TestData\**" />
    <Content Include="TestData\**">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>