<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net$(NETCoreAppMaximumVersion)</TargetFramework>
  </PropertyGroup>

  <ItemGroup Condition="'$(PACK)'!='true'">
    <ProjectReference Include="..\..\src\War3Net.CodeAnalysis.VJass\War3Net.CodeAnalysis.VJass.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(PACK)'=='true'">
    <PackageReference Include="War3Net.CodeAnalysis.VJass" />
  </ItemGroup>

</Project>
