<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TfmGroupDotNet)</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Transpile JASS to C# or Lua.</Description>
    <PackageTags>csharp;jass;lua;modding;warcraft3;wc3</PackageTags>
  </PropertyGroup>

  <ItemGroup Condition="'$(PUBLISH)'!='true'">
    <ProjectReference Include="..\War3Net.CodeAnalysis.Jass\War3Net.CodeAnalysis.Jass.csproj" />
    <ProjectReference Include="..\..\submodules\CSharp.lua\CSharp.lua\CSharp.lua.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(PUBLISH)'=='true'">
    <PackageReference Include="War3Net.CodeAnalysis.Jass" />
    <PackageReference Include="War3Net.CSharpLua" />
  </ItemGroup>

</Project>
