<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net$(NETCoreAppMaximumVersion)</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup Condition="'$(PACK)'!='true'">
    <ProjectReference Include="..\..\src\War3Net.Modeling\War3Net.Modeling.csproj" />
    <ProjectReference Include="..\..\submodules\FastMDX\FastMDX\FastMDX.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(PACK)'=='true'">
    <PackageReference Include="War3Net.Modeling" />
    <!-- TODO: PackageReference instead of ProjectReference -->
    <ProjectReference Include="..\..\submodules\FastMDX\FastMDX\FastMDX.csproj" />
  </ItemGroup>

</Project>
