<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TfmGroupDotNet)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiffPlex" />
  </ItemGroup>

  <ItemGroup Condition="'$(PACK)'!='true'">
    <ProjectReference Include="..\..\src\War3Net.Build.Core\War3Net.Build.Core.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(PACK)'=='true'">
    <PackageReference Include="War3Net.Build.Core" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="TestData/Script/**" />
    <Content Remove="TestData/Script/**" />
    <Compile Remove="TestData/Transpilation/**" />
    <Content Remove="TestData/Transpilation/**" />
  </ItemGroup>

</Project>
