<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TfmGroupDotNet)</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Read and write MPQ archives.</Description>
    <PackageTags>modding;mpq;warcraft3;wc3</PackageTags>
  </PropertyGroup>

  <ItemGroup Condition="'$(PUBLISH)'!='true'">
    <ProjectReference Include="..\War3Net.IO.Compression\War3Net.IO.Compression.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(PUBLISH)'=='true'">
    <PackageReference Include="War3Net.IO.Compression" />
  </ItemGroup>

</Project>
