<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <TargetFrameworks>$(TfmGroupDotNetWindows)</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Render Warcraft III models using Veldrid.</Description>
    <PackageTags>modding;rendering;warcraft3;wc3</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pfim" />
    <PackageReference Include="Veldrid" />
    <PackageReference Include="Veldrid.ImGui" />
    <PackageReference Include="Veldrid.SPIRV" />
    <PackageReference Include="Veldrid.StartupUtilities" />
    <PackageReference Include="Veldrid.Utilities" />
  </ItemGroup>

  <ItemGroup Condition="'$(PUBLISH)'!='true'">
    <ProjectReference Include="..\War3Net.Drawing.Blp\War3Net.Drawing.Blp.csproj" />
    <ProjectReference Include="..\War3Net.Modeling\War3Net.Modeling.csproj" />
    <ProjectReference Include="..\..\submodules\FastMDX\FastMDX\FastMDX.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(PUBLISH)'=='true'">
    <PackageReference Include="War3Net.Drawing.Blp" />
    <PackageReference Include="War3Net.Modeling" />
    <!-- todo: packagereference -->
    <ProjectReference Include="..\..\submodules\FastMDX\FastMDX\FastMDX.csproj" />
  </ItemGroup>

</Project>
