global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Text;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using War3Net.Common.Extensions;
global using War3Net.Modeling.DataStructures;
global using War3Net.Modeling.Enums;
