global using System;
global using System.Collections.Generic;
global using System.CommandLine;
global using System.CommandLine.Parsing;
global using System.IO;
global using System.Linq;
global using System.Security.Cryptography;
global using System.Text.Json;
global using System.Threading.Tasks;
global using War3Net.IO.Mpq;
global using War3Net.Tools.Cli.Mpq;
global using static War3Net.Tools.Cli.OptionFactory;