<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net$(NETCoreAppMaximumVersion)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\War3Net.IO.Casc\War3Net.IO.Casc.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.8" />
  </ItemGroup>

  <!--<ItemGroup Condition="'$(Configuration)'=='Debug'">
    <ProjectReference Include="..\..\src\War3Net.IO.Casc\War3Net.IO.Casc.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'=='Release'">
    <PackageReference Include="War3Net.IO.Casc" Version="$(War3NetIOCascVersion)" />
  </ItemGroup>-->

</Project>
