<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net$(NETCoreAppMaximumVersion)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\War3Net.IO.Casc\War3Net.IO.Casc.csproj" />
  </ItemGroup>

  <!--<ItemGroup Condition="'$(PACK)'!='true'">
    <ProjectReference Include="..\..\src\War3Net.IO.Casc\War3Net.IO.Casc.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(PACK)'=='true'">
    <PackageReference Include="War3Net.IO.Casc" />
  </ItemGroup>-->

</Project>
