<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net$(NETCoreAppMaximumVersion)</TargetFramework>
  </PropertyGroup>

  <ItemGroup Condition="'$(PACK)'!='true'">
    <ProjectReference Include="..\..\src\War3Net.Replay\War3Net.Replay.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(PACK)'=='true'">
    <PackageReference Include="War3Net.Replay" />
  </ItemGroup>

</Project>
