<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TfmGroupDotNet)</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Read and write SLK data files.</Description>
    <PackageTags>modding;slk;sylk;warcraft3;wc3</PackageTags>
  </PropertyGroup>

  <ItemGroup Condition="'$(PACK)'!='true'">
    <ProjectReference Include="..\War3Net.Common\War3Net.Common.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(PACK)'=='true'">
    <PackageReference Include="War3Net.Common" />
  </ItemGroup>

</Project>
