<Project>
  <PropertyGroup>
    <PackageIcon>war3net-icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup Condition="'$(PUBLISH)'=='true'">
    <None Include="$(MSBuildThisFileDirectory)../assets/images/war3net-icon.png" Pack="true" PackagePath="\" Visible="false" />
    <None Include="$(MSBuildProjectDirectory)/README.md" Pack="true" PackagePath="\" Visible="true" />
  </ItemGroup>
</Project>