<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(TfmGroupDotNet)</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup>
		<Description>Helper methods for Pidgin parsers.</Description>
		<PackageTags>modding;parser;syntax;warcraft3;wc3</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Pidgin" />
	</ItemGroup>

</Project>
