<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(TfmGroupDotNet)</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup>
		<Description>Shared classes for JASS/vJASS packages.</Description>
		<PackageTags>modding;parser;syntax;warcraft3;wc3</PackageTags>
	</PropertyGroup>

</Project>
