name: Pack NuGet Packages

on:
  pull_request:
    branches: ['master']
  workflow_dispatch:
    inputs:
      version_suffix:
        description: 'Version suffix for packages (e.g., beta, rc1)'
        required: false
        type: string

env:
  DOTNET_VERSION: '8.0.x'
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-and-pack:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup local NuGet feed
      run: |
        # Create artifacts folder for local NuGet feed
        mkdir -p ./artifacts
        echo "Local NuGet feed directory created at: $(pwd)/artifacts"
        
        # List configured sources
        echo "Configured NuGet sources:"
        dotnet nuget list source

    - name: Build and pack in dependency order
      run: |
        chmod +x .github/scripts/build-and-pack-nuget.sh
        .github/scripts/build-and-pack-nuget.sh "${{ github.event.inputs.version_suffix }}"